version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts: 
      # 상대경로 수정
      device: ../home/yejinkim/data/mariadb
      type: none
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      # 상대경로 수정
      device: ../home/yejinkim/data/wordpress
      type: none
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
